//CYPRESS PARA TESTEAR EL FUNCIONAMIENTO DE LA PAGINA
export const AUTH_START = "AUTH_START";
export const AUTH_SUCESS = "AUTH_SUCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const API_START = "API_START";
export const API_SUCCESS = "API_SUCCESS";
export const API_FAIL = "API_FAIL";
export const API_GET_TOTALS = "API_GET_TOTALS";
export const API_GET_EARNINGS = "API_GET_EARNINGS";
export const API_UPDATED = "API_UPDATED";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const RESET_ORDER_FILTER = "RESET_ORDER_FILTER";
export const TOGGLE_SIDEDRAWER = "TOGGLE_SIDEDRAWER";
